remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Renato C. Torres
description: Optical Spectroscopy & Embedded Systems Research
theme: minimal
